### ISSUE TITLE
Addition of VisualMRC to this repository

### ISSUE THREAD

**Issue by rtanaka-lab** [xinke-wang/Awesome-Text-VQA#3]
Hi,

Can you please add my AAAI21 paper [VisualMRC: Machine Reading Comprehension on Document Images](https://arxiv.org/abs/2101.11272) to this repository?
Our project page is at https://github.com/nttmdlab-nlp/VisualMRC, and the dataset can be obtained if you contact me.

**Comment by xinke-wang** [comment]
Hi,

I've added this paper. But I didn't find the exact image number for each split in the paper, i.e., x for training split; y for developing; z for testing. Could you give me this information so I can update it to the repository.

**Comment by rtanaka-lab** [comment]
Thank you for adding my paper to this repository.
The VisaulMRC dataset contains 7013 (train), 947 (dev),  and 2237 (test) images.

**Comment by xinke-wang** [comment]
Thank you for your response. I've updated the image number.
